name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - papermill
  - pandas
  - matplotlib
  - openpyxl
  - s3fs
  - plotly
  - langchain
  - langchain-openai
  - yfinance
  - sentence-transformers
  - ipywidgets
  - pip:
      - chromadb
      - dataframe-image
      - pymilvus
      - langchain-community